# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: 'rocker/r-ver:3.6.2'

steps:
- script: |
    apt-get -y build-dep libcurl4-gnutls-dev
    apt-get -y install libcurl4-gnutls-dev
  displayName: 'Download libcurl4-gnutls-dev'

- script: Rscript -e 'R.version'
  displayName: 'R Version'

- script: Rscript -e 'dir.create("library"); install.packages("devtools", lib = "library"); library("devtools"); devtools::check()'
  displayName: 'Package Check'
