# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-16.04'

container: 'rocker/tidyverse:latest'

steps:
- script: Rscript -e 'R.version'
  displayName: 'R Version'

- script: sudo Rscript -e 'install.packages(c("huxtable", "kableExtra")); devtools::test()'
  displayName: 'Package Check'

